
[functions.send-reminder]
enabled = true
verify_jwt = true
import_map = "./functions/send-reminder/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-reminder/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-reminder/*.html" ]
[functions.send-reminders]
# This cron expression means "at minute 0 of every hour".
# Runs at 08:00, 09:00, 10:00, etc.
schedule = "0 * * * *"
